/** Splash Zone – palette and layout. Only these colors; container max-w-6xl. */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--color-bg)",
        surface: "var(--color-surface)",
        primary: "var(--color-primary)",
        primaryDark: "var(--color-primaryDark)",
        footer: "var(--color-footer)",
        cta: "var(--color-cta)",
        ctaHover: "var(--color-ctaHover)",
        success: "var(--color-success)",
        text: "var(--color-text)",
        muted: "var(--color-muted)",
        border: "var(--color-border)",
        promoBg: "var(--color-promoBg)",
        promoBorder: "var(--color-promoBorder)",
        footerDeep: "var(--color-footer)",
        "promo-bg": "var(--color-promoBg)",
        "promo-border": "var(--color-promoBorder)",
        "brand-bg": "var(--color-bg)",
        "brand-bg-alt": "var(--color-promoBg)",
        "brand-blue": "var(--color-primary)",
        "brand-blue-deep": "var(--color-primaryDark)",
        "brand-orange": "var(--color-cta)",
        "brand-orange-hover": "var(--color-ctaHover)",
        "brand-green": "var(--color-success)",
        "brand-text": "var(--color-text)",
        "brand-muted": "var(--color-muted)",
        "brand-urgency": "var(--color-cta)",
        "brand-guarantee": "rgba(34, 197, 94, 0.2)",
        "brand-faq": "var(--color-surface)",
        "brand-gold": "#eab308",
        "brand-gray": "var(--color-muted)",
      },
      fontSize: {
        "h1": ["2rem", { lineHeight: "1.2" }],
        "h1-lg": ["2.5rem", { lineHeight: "1.2" }],
        "h2": ["1.375rem", { lineHeight: "1.3" }],
        "h2-lg": ["1.75rem", { lineHeight: "1.3" }],
      },
    },
  },
  plugins: [],
};
